<?php
$host="localhost";
$user="root";
$pass="";
$database="db_project";

$sql=new mysqli($host,$user,$pass,$database);

if($sql->connect_error)
{
    die ("Unsucessful");
}
echo "Connection made";
$query='create table animals(AID INT AUTO_INCREMENT,TYPE varchar(20),BREED varchar(30),WEIGHT float(3),
PRIMARY KEY (AID));
ALTER TABLE ANIMALS 
ADD QUANTITY INT DEFAULT 0;
alter table animals add unique(type,breed);
create table pet_provider(PRO_ID INT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(20),PH1 varchar(10) NOT NULL,
PH2 varchar(10) DEFAULT NULL);
ALTER TABLE PET_PROVIDER ADD UNIQUE(PH1);
CREATE TABLE pet (P_ID INT PRIMARY KEY AUTO_INCREMENT,
COLOR VARCHAR(10) DEFAULT NULL,
PIC VARCHAR(40) DEFAULT NULL,
PRICE INT DEFAULT 600,
 CHECK(PRICE > 500),
AVALABILITY VARCHAR(1) DEFAULT \'N\',
PRO_ID INT NOT NULL,
A_ID INT NOT NULL,
FOREIGN KEY(PRO_ID) REFERENCES PET_PROVIDER(PRO_ID),
FOREIGN KEY(A_ID) REFERENCES ANIMALS(AID));
CREATE TABLE COSTUMERS(
    USER_ID int auto_increment PRIMARY KEY,    
    EMAIL VARCHAR(40),
    PASS VARCHAR(40) NOT NULL,
    NAME VARCHAR(20),
    PIC VARCHAR(40)DEFAULT NULL,
    CITY VARCHAR(20) NOT NULL,
    ADRESS VARCHAR(400) NOT NULL,
    DOB DATE,
    GENDER VARCHAR(1) DEFAULT \'M\',
    CHECK(GENDER=\'M\' OR GENDER=\'F\' OR GENDER =\'O\'));
CREATE TABLE CART(
USER_ID INT NOT NULL,
PET_ID INT NOT NULL,
final VARCHAR(1) DEFAULT \'N\',
FOREIGN KEY (PET_ID) REFERENCES PET(P_ID),
FOREIGN KEY (USER_ID) REFERENCES COSTUMERS(USER_ID),
PRIMARY KEY (USER_ID,PET_ID));

INSERT INTO ANIMALS(TYPE,BREED,WEIGHT,QUANTITY) VALUES("Dog","German Shepherd",35,15);
INSERT INTO ANIMALS(TYPE,BREED,WEIGHT,QUANTITY) VALUES("Dog","Bull Dog",23,20);
INSERT INTO ANIMALS(TYPE,BREED,WEIGHT,QUANTITY) VALUES("Dog","Golden Retriever",33,2);
INSERT INTO ANIMALS(TYPE,BREED,WEIGHT,QUANTITY) VALUES("Dog","Doberman Pinscher",38,11);
INSERT INTO ANIMALS(TYPE,BREED,WEIGHT,QUANTITY) VALUES("Dog","St. Bernard",72,6);
INSERT INTO ANIMALS(TYPE,BREED,WEIGHT,QUANTITY) VALUES("Dog","Siberian Husky",18,7);
INSERT INTO ANIMALS(TYPE,BREED,WEIGHT,QUANTITY) VALUES("Dog","bernese mountain dog",38,8);
INSERT INTO ANIMALS(TYPE,BREED,WEIGHT,QUANTITY) VALUES("Dog","chow chow",36,4);
INSERT INTO ANIMALS(TYPE,BREED,WEIGHT,QUANTITY) VALUES("Dog","boxer",26,13);
INSERT INTO ANIMALS(TYPE,BREED,WEIGHT,QUANTITY) VALUES("Dog","dalmatian",18,23);
INSERT INTO ANIMALS(TYPE,BREED,WEIGHT,QUANTITY) VALUES("Cat","Russian blue",3.5,21);
INSERT INTO ANIMALS(TYPE,BREED,WEIGHT,QUANTITY) VALUES("Cat","Persian cat",4.2,12);
INSERT INTO ANIMALS(TYPE,BREED,WEIGHT,QUANTITY) VALUES("Cat","Ragdoll",8.5,6);
INSERT INTO ANIMALS(TYPE,BREED,WEIGHT,QUANTITY) VALUES("Cat","Munchkin",6,8);
INSERT INTO ANIMALS(TYPE,BREED,WEIGHT,QUANTITY) VALUES("Cat","Scottish Fold",5.2,9);

INSERT INTO ANIMALS(TYPE,BREED,WEIGHT,QUANTITY) VALUES("Rabbit","Mini Rex",1.1,8);
INSERT INTO ANIMALS(TYPE,BREED,WEIGHT,QUANTITY) VALUES("Rabbit","American Fuzzy Lop",4.3,6);
INSERT INTO ANIMALS(TYPE,BREED,WEIGHT,QUANTITY) VALUES("Rabbit","Dwarf Hotot",3.2,6);
INSERT INTO ANIMALS(TYPE,BREED,WEIGHT,QUANTITY) VALUES("Rabbit","Mini Lop.",5.3,12);
INSERT INTO ANIMALS(TYPE,BREED,WEIGHT,QUANTITY) VALUES("Rabbit","Netherland Dwarf.",2.1,10);
INSERT INTO PET_PROVIDER(NAME,PH1,PH2) VALUES ("Rahul","9599618707","9990322752");
INSERT INTO PET_PROVIDER(NAME,PH1) VALUES ("Ashish","8826597899");
INSERT INTO PET_PROVIDER(NAME,PH1,PH2) VALUES ("Saurav","8368373355","8076266966");
INSERT INTO PET_PROVIDER(NAME,PH1,PH2) VALUES ("Vibhuti","8299876795","8953813600");
INSERT INTO PET_PROVIDER(NAME,PH1) VALUES ("Naman","7043430525");


INSERT INTO PET(COLOR,PIC,PRICE,AVALABILITY,PRO_ID,A_ID) VALUES ("Brown","GermanShephard1.jpg",4250,"Y",2,1);
INSERT INTO PET(COLOR,PIC,PRICE,AVALABILITY,PRO_ID,A_ID) VALUES ("lightBrown","GermanLightBR2.jpg",4200,"Y",2,1);
INSERT INTO PET(COLOR,PIC,PRICE,AVALABILITY,PRO_ID,A_ID) VALUES ("Black","GermanShBlack3.jpg",4200,"Y",2,1);
INSERT INTO PET(COLOR,PIC,PRICE,AVALABILITY,PRO_ID,A_ID) VALUES ("Brown","GermanDarkBr4.jpg",4500,"Y",3,1);
INSERT INTO PET(COLOR,PIC,PRICE,AVALABILITY,PRO_ID,A_ID) VALUES ("Brown","GermanShephard1.jpg",4250,"N",3,1);

Alter table pet
 modify color varchar(30) default NULL;
INSERT INTO PET(COLOR,PIC,PRICE,AVALABILITY,PRO_ID,A_ID) VALUES ("Brown","BullDogBrown.jpg",5000,"y",4,2);
INSERT INTO PET(COLOR,PIC,PRICE,AVALABILITY,PRO_ID,A_ID) VALUES ("White","BullDogWhite.jpg",7000,"y",4,2);
INSERT INTO PET(COLOR,PIC,PRICE,AVALABILITY,PRO_ID,A_ID) VALUES ("White+Brown","BullDogWh+Br.jpg",6500,"y",4,2);
INSERT INTO PET(COLOR,PIC,PRICE,AVALABILITY,PRO_ID,A_ID) VALUES ("Black","BullDogBlack.jpg",6500,"y",3,2);
INSERT INTO PET(COLOR,PIC,PRICE,AVALABILITY,PRO_ID,A_ID) VALUES ("Cream","BullDogCream.jpg",7200,"y",4,2);
INSERT INTO PET(COLOR,PIC,PRICE,AVALABILITY,PRO_ID,A_ID) VALUES ("White","BulldogWhite12.jpg",4500,"y",4,2);
INSERT INTO PET(COLOR,PIC,PRICE,AVALABILITY,PRO_ID,A_ID) VALUES ("Brown","BullDog123.jpg",5500,"y",3,2);
INSERT INTO PET(COLOR,PIC,PRICE,AVALABILITY,PRO_ID,A_ID) VALUES ("white+Brown","BullDog45.jpg",3900,"n",4,2);
INSERT INTO PET(COLOR,PIC,PRICE,AVALABILITY,PRO_ID,A_ID) VALUES ("White","BullDog99.jpg",7200,"y",4,2);
INSERT INTO PET(COLOR,PIC,PRICE,AVALABILITY,PRO_ID,A_ID) VALUES ("Brown","ChowChow1.jpg",6700,"y",5,8);
INSERT INTO PET(COLOR,PIC,PRICE,AVALABILITY,PRO_ID,A_ID) VALUES ("Cream","ChowChow2.jpg",4500,"y",5,8);
INSERT INTO PET(COLOR,PIC,PRICE,AVALABILITY,PRO_ID,A_ID) VALUES ("Black","ChowChow3.jpg",8000,"y",5,8);
INSERT INTO PET(COLOR,PIC,PRICE,AVALABILITY,PRO_ID,A_ID) VALUES ("White+Brown","Boxer1,jpg",11000,"y",2,9);
INSERT INTO PET(COLOR,PIC,PRICE,AVALABILITY,PRO_ID,A_ID) VALUES ("White","Boxer2.jpg",10000,"y",2,9);
INSERT INTO PET(COLOR,PIC,PRICE,AVALABILITY,PRO_ID,A_ID) VALUES ("White+black","Siberian1.jpg",12500,"y",1,6);
INSERT INTO PET(COLOR,PIC,PRICE,AVALABILITY,PRO_ID,A_ID) VALUES ("Cream","husky10.jpg",13500,"y",1,6);


INSERT INTO PET(COLOR,PIC,PRICE,AVALABILITY,PRO_ID,A_ID) VALUES ("Brown+White","st.bernard1.jpg",11500,"y",2,5);
INSERT INTO PET(COLOR,PIC,PRICE,AVALABILITY,PRO_ID,A_ID) VALUES ("Creme+Brown","bernard2.jpg",10500,"y",1,6);
INSERT INTO PET(COLOR,PIC,PRICE,AVALABILITY,PRO_ID,A_ID) VALUES ("Grey","RussianBlue1.jpg",3500,"y",5,11);
INSERT INTO PET(COLOR,PIC,PRICE,AVALABILITY,PRO_ID,A_ID) VALUES ("Grey","russian2.jpg",3700,"y",5,11);
INSERT INTO PET(COLOR,PIC,PRICE,AVALABILITY,PRO_ID,A_ID) VALUES ("White","Persian1.jpg",3200,"y",5,12);
INSERT INTO PET(COLOR,PIC,PRICE,AVALABILITY,PRO_ID,A_ID) VALUES ("Brown","Persian2.jpg",4800,"y",5,12);
INSERT INTO PET(COLOR,PIC,PRICE,AVALABILITY,PRO_ID,A_ID) VALUES ("Black","Persian3.jpg",4800,"y",5,12);
INSERT INTO PET(COLOR,PIC,PRICE,AVALABILITY,PRO_ID,A_ID) VALUES ("White","Rang1.jpg",5600,"y",5,13);
INSERT INTO PET(COLOR,PIC,PRICE,AVALABILITY,PRO_ID,A_ID) VALUES ("Brown+White","Rang2.jpg",5700,"y",5,13);
INSERT INTO PET(COLOR,PIC,PRICE,AVALABILITY,PRO_ID,A_ID) VALUES ("Brown+White","munch1.jpg",4500,"y",3,14);
INSERT INTO PET(COLOR,PIC,PRICE,AVALABILITY,PRO_ID,A_ID) VALUES ("Brown+White","munchkin2.jpg",6700,"y",3,14);
INSERT INTO PET(COLOR,PIC,PRICE,AVALABILITY,PRO_ID,A_ID) VALUES ("Grey","Scot1.jpg",6300,"y",3,15);
INSERT INTO PET(COLOR,PIC,PRICE,AVALABILITY,PRO_ID,A_ID) VALUES ("Brown+White","Scot2.jpg",6400,"y",3,15);
INSERT INTO PET(COLOR,PIC,PRICE,AVALABILITY,PRO_ID,A_ID) VALUES ("Black","Scot3.jpg",7000,"y",3,15);
INSERT INTO PET(COLOR,PIC,PRICE,AVALABILITY,PRO_ID,A_ID) VALUES ("Black","Rex1.jpg",4600,"y",4,16);
INSERT INTO PET(COLOR,PIC,PRICE,AVALABILITY,PRO_ID,A_ID) VALUES ("White","Rex2.jpg",4600,"y",4,16);
INSERT INTO PET(COLOR,PIC,PRICE,AVALABILITY,PRO_ID,A_ID) VALUES ("Brown","Rex3.jpg",5000,"y",4,16);
INSERT INTO PET(COLOR,PIC,PRICE,AVALABILITY,PRO_ID,A_ID) VALUES ("White+Brown","fuzzyLop1.jpg",3500,"y",4,17);
INSERT INTO PET(COLOR,PIC,PRICE,AVALABILITY,PRO_ID,A_ID) VALUES ("White+Grey","fuzzyLop2.jpg",3800,"y",4,17);
INSERT INTO PET(COLOR,PIC,PRICE,AVALABILITY,PRO_ID,A_ID) VALUES ("White+Brown","fuzzyLop1.jpg",3500,"y",4,17);
INSERT INTO PET(COLOR,PIC,PRICE,AVALABILITY,PRO_ID,A_ID) VALUES ("White","Hatot1.jpg",3500,"y",3,18);
INSERT INTO PET(COLOR,PIC,PRICE,AVALABILITY,PRO_ID,A_ID) VALUES ("Cream","Hatot2.jpg",3900,"y",3,18);
INSERT INTO PET(COLOR,PIC,PRICE,AVALABILITY,PRO_ID,A_ID) VALUES ("White+Black","Hatot34.jpg",3400,"y",3,18);
INSERT INTO PET(COLOR,PIC,PRICE,AVALABILITY,PRO_ID,A_ID) VALUES ("Brown","miniLop1.jpg",4000,"y",3,19);
INSERT INTO PET(COLOR,PIC,PRICE,AVALABILITY,PRO_ID,A_ID) VALUES ("Grey","minilop2.jpg",3800,"y",3,19);
INSERT INTO PET(COLOR,PIC,PRICE,AVALABILITY,PRO_ID,A_ID) VALUES ("White","miniLop3.jpg",3900,"y",3,19);
INSERT INTO PET(COLOR,PIC,PRICE,AVALABILITY,PRO_ID,A_ID) VALUES ("Brown","Nither1.jpg",3200,"y",3,20);
INSERT INTO PET(COLOR,PIC,PRICE,AVALABILITY,PRO_ID,A_ID) VALUES ("Black+Grey","nither2.jpg",4300,"y",3,20);

create table reviews(firstname varchar(20),lastname varchar(20),message varchar(500),primary key(firstname,lastname,message));
delimiter $
create trigger avalability2
	after update on cart
	for each row 	
	begin
	if new.final=\'y\' then
	update pet set avalability=\'n\'
	where p_id=new.pet_id;
	
	update animals set 
	quantity =quantity-1 where
	aid=(select aid from pet where p_id=new.pet_id);
  end if;
end$
delimiter $
create trigger avalability1
	after update on cart
	for each row 	
	begin
	if new.final=\'n\' then
	update pet set avalability=\'y\'
	where p_id=new.pet_id;
	
	update animals set 
	quantity =quantity+1 where
	aid=(select aid from pet where p_id=new.pet_id);
  end if;
end$
';
if($sql->multi_query($query)==TRUE)
{
    echo ("Query Executed Sucessfully");
}
else
{
    echo(mysqli_error($sql));
}